## Библиотеки

In [1]:
# Загружаем необходимые библиотеки
import pandas as pd
import numpy as np

# Посомтреть директория компа
import os
current_dir = os.getcwd()
print(current_dir)

In [2]:
# Убрать предупреждения
import warnings
warnings.filterwarnings('ignore')

## Загрузка данных

In [5]:
PATH_OUT = r'C:\Users\Dell\Desktop\MyPython\Школьники\Текущие материалы\Материалы\Тема_1'

In [10]:
# Загрузка данных в csv формате
df = pd.read_csv(PATH_OUT + '\\tema_13_teor.csv', sep=';', encoding='cp1251', ) #encoding='utf-8'
# df = df.dropna()  # удалили строки с пропусками
# df..... # команда, позволяющая вывести

In [11]:
df.head(15)

,Пол,Возраст,Путешествует с детьми,Расстояние,Включён завтрак,Наличие wifi,Оценка удобства добирания до места,Оценка интерсности досуга,Оценка качества питания,Оценка качества wifi,Оценка комфортности палатки,Общая оценка качества предоставленной услуги
0,муж,"55,9",нет,677,0,1,2,плохо,отсутствует,плохо,плохо,нормально
1,жен,"37,4",нет,2112,1,0,3,плохо,плохо,отсутствует,хорошо,нормально
2,жен,"48,3",да,1241,1,1,3,нормально,нормально,плохо,плохо,нормально
3,муж,"58,6",да,1579,1,1,4,нормально,плохо,нормально,хорошо,нормально
4,муж,"34,3",нет,469,0,1,4,нормально,отсутствует,плохо,нормально,нормально
5,муж,"33,3",нет,667,0,0,4,плохо,отсутствует,отсутствует,нормально,нормально
6,жен,"45,2",нет,865,1,1,4,хорошо,плохо,хорошо,нормально,хорошо
7,жен,"42,5",нет,1242,0,1,4,нормально,отсутствует,плохо,нормально,нормально
8,жен,"24,2",нет,1079,1,1,3,нормально,плохо,плохо,нормально,нормально
9,муж,"45,2",нет,627,1,0,2,плохо,нормально,отсутствует,нормально,нормально
10,муж,"51,6",да,1747,1,1,3,нормально,,плохо,хорошо,нормально
11,муж,"37,4",нет,195,1,1,3,нормально,плохо,плохо,плохо,плохо
12,жен,"65,9",нет,680,1,0,2,плохо,плохо,отсутствует,нормально,нормально
13,жен,"19,7",нет,287,0,0,3,,отсутствует,отсутствует,нормально,нормально
14,муж,"22,2",нет,785,1,1,2,нормально,нормально,нормально,нормально,хорошо

In [61]:
df.isna().sum()

Пол                                             0
Возраст                                         0
Путешествует с детьми                           0
Расстояние                                      0
Включён завтрак                                 0
Наличие wifi                                    0
Оценка удобства добирания до места              0
Оценка интерсности досуга                       0
Оценка качества питания                         0
Оценка качества wifi                            0
Оценка комфортности палатки                     0
Общая оценка качества предоставленной услуги    0
dtype: int64

In [ ]:
# а если вывести несколько столбцов?
df[['столбец_1', 'столбец_2']]

In [62]:
dd = df['Пол'].name

In [63]:
dd

'Пол'

In [22]:
dd.lower()

'пол'

In [65]:
df['Путешествует с детьми'].name.replace(' ', '_')

'Путешествует_с_детьми'

In [24]:
# можно вывести названия колонок
df.columns =

Index(['Пол', 'Возраст', 'Путешествует с детьми', 'Расстояние',
       'Включён завтрак', 'Наличие wifi', 'Оценка удобства добирания до места',
       'Оценка интерсности досуга', 'Оценка качества питания',
       'Оценка качества wifi', 'Оценка комфортности палатки',
       'Общая оценка качества предоставленной услуги'],
      dtype='object')

#### привести названия колонок к PEP8

In [11]:
df.head(3)

,пол,возраст,путешествует_с_детьми,расстояние,включён_завтрак,наличие_wifi,оценка_удобства_добирания_до_места,оценка_интерсности_досуга,оценка_качества_питания,оценка_качества_wifi,оценка_комфортности_палатки,общая_оценка_качества_предоставленной_услуги
0,муж,"55,9",нет,677,0,1,2,плохо,отсутствует,плохо,плохо,нормально
1,жен,"37,4",нет,2112,1,0,3,плохо,плохо,отсутствует,хорошо,нормально
2,жен,"48,3",да,1241,1,1,3,нормально,нормально,плохо,плохо,нормально

#### Изучение типов данных

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2999 entries, 0 to 2998
Data columns (total 12 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Пол                                           2999 non-null   object
 1   Возраст                                       2999 non-null   object
 2   Путешествует с детьми                         2999 non-null   object
 3   Расстояние                                    2999 non-null   int64
 4   Включён завтрак                               2999 non-null   int64
 5   Наличие wifi                                  2999 non-null   int64
 6   Оценка удобства добирания до места            2999 non-null   int64
 7   Оценка интерсности досуга                     2999 non-null   object
 8   Оценка качества питания                       2999 non-null   object
 9   Оценка качества wifi                          2999 non-null   object
 10  Оценка комфортности палатки                   2999 non-null   object
 11  Общая оценка качества предоставленной услуги  2999 non-null   object
dtypes: int64(4), object(8)
memory usage: 281.3+ KB

In [ ]:
# конструкция для изменения типов данных
df['столбец'].astype(float) # (int/object)

In [ ]:
round(df['Возраст'], 0).astype(int)

## Перевод в категориальгные шкалы

In [27]:
df.head(4)

,Пол,Возраст,Путешествует с детьми,Расстояние,Включён завтрак,Наличие wifi,Оценка удобства добирания до места,Оценка интерсности досуга,Оценка качества питания,Оценка качества wifi,Оценка комфортности палатки,Общая оценка качества предоставленной услуги
0,муж,"55,9",нет,677,0,1,2,плохо,отсутствует,плохо,плохо,нормально
1,жен,"37,4",нет,2112,1,0,3,плохо,плохо,отсутствует,хорошо,нормально
2,жен,"48,3",да,1241,1,1,3,нормально,нормально,плохо,плохо,нормально
3,муж,"58,6",да,1579,1,1,4,нормально,плохо,нормально,хорошо,нормально

In [66]:
df['расст_кат'] = df['Расстояние'].apply(lambda x: 'близко' if x <= 500 else 'далеко')

In [67]:
df.head(4)

,Пол,Возраст,Путешествует с детьми,Расстояние,Включён завтрак,Наличие wifi,Оценка удобства добирания до места,Оценка интерсности досуга,Оценка качества питания,Оценка качества wifi,Оценка комфортности палатки,Общая оценка качества предоставленной услуги,расст_кат
0,муж,"55,9",нет,677,0,1,2,плохо,отсутствует,плохо,плохо,нормально,далеко
1,жен,"37,4",нет,2112,1,0,3,плохо,плохо,отсутствует,хорошо,нормально,далеко
2,жен,"48,3",да,1241,1,1,3,нормально,нормально,плохо,плохо,нормально,далеко
3,муж,"58,6",да,1579,1,1,4,нормально,плохо,нормально,хорошо,нормально,далеко

## Посчитать количество категориальных данных

In [68]:
df['расст_кат'].value_counts()

далеко    1933
близко    1066
Name: расст_кат, dtype: int64

### Выбрать группу данных для работы

In [32]:
df[df['Общая оценка качества предоставленной услуги'] == 'плохо']

,Пол,Возраст,Путешествует с детьми,Расстояние,Включён завтрак,Наличие wifi,Оценка удобства добирания до места,Оценка интерсности досуга,Оценка качества питания,Оценка качества wifi,Оценка комфортности палатки,Общая оценка качества предоставленной услуги,расст_кат
11,муж,"37,4",нет,195,1,1,3,нормально,плохо,плохо,плохо,плохо,менее_500
22,муж,"64,2",нет,688,1,0,2,плохо,плохо,отсутствует,нормально,плохо,более_500
23,муж,"41,6",нет,705,0,1,2,нормально,отсутствует,плохо,плохо,плохо,более_500
33,жен,"36,7",нет,456,1,1,3,нормально,плохо,плохо,нормально,плохо,менее_500
37,жен,"21,6",нет,157,1,0,2,плохо,плохо,отсутствует,плохо,плохо,менее_500
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2951,муж,"37,7",нет,292,1,1,1,плохо,плохо,плохо,хорошо,плохо,менее_500
2961,муж,"28,6",нет,2255,1,1,2,нормально,плохо,плохо,хорошо,плохо,более_500
2973,муж,"27,9",нет,196,0,0,2,плохо,отсутствует,отсутствует,плохо,плохо,менее_500
2981,жен,"32,3",нет,973,1,1,4,нормально,плохо,нормально,хорошо,плохо,более_500
2982,жен,"35,3",нет,944,1,1,3,нормально,плохо,плохо,нормально,плохо,более_500

In [33]:
df[df['Расстояние'] > 500]

,Пол,Возраст,Путешествует с детьми,Расстояние,Включён завтрак,Наличие wifi,Оценка удобства добирания до места,Оценка интерсности досуга,Оценка качества питания,Оценка качества wifi,Оценка комфортности палатки,Общая оценка качества предоставленной услуги,расст_кат
0,муж,"55,9",нет,677,0,1,2,плохо,отсутствует,плохо,плохо,нормально,более_500
1,жен,"37,4",нет,2112,1,0,3,плохо,плохо,отсутствует,хорошо,нормально,более_500
2,жен,"48,3",да,1241,1,1,3,нормально,нормально,плохо,плохо,нормально,более_500
3,муж,"58,6",да,1579,1,1,4,нормально,плохо,нормально,хорошо,нормально,более_500
5,муж,"33,3",нет,667,0,0,4,плохо,отсутствует,отсутствует,нормально,нормально,более_500
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2992,муж,"38,9",нет,1274,0,1,5,нормально,отсутствует,плохо,нормально,нормально,более_500
2993,муж,"40,4",нет,983,1,1,2,плохо,нормально,нормально,плохо,хорошо,более_500
2994,муж,"40,8",нет,1061,1,1,2,нормально,нормально,плохо,нормально,нормально,более_500
2996,жен,"40,8",да,552,0,1,4,нормально,отсутствует,нормально,плохо,нормально,более_500
2997,жен,"49,4",да,2622,1,0,4,плохо,плохо,отсутствует,нормально,нормально,более_500

## Группировка данных

In [ ]:
Расстояние

In [72]:
df.groupby(['Пол','Путешествует с детьми'])['Расстояние'].agg(sum)

Пол  Путешествует с детьми
жен  да                       283961
     нет                      994246
муж  да                       279569
     нет                      950505
Name: Расстояние, dtype: int64

In [44]:
df.groupby(['Пол'])['Расстояние'].agg(['sum', 'min', 'max'])

         sum  min   max
Пол
жен  1278207   68  4030
муж  1230074  104  4539

In [36]:
df.groupby(['Пол']).size()

Пол
жен    1521
муж    1478
dtype: int64

In [37]:
df['Пол'].value_counts()

жен    1521
муж    1478
Name: Пол, dtype: int64

In [ ]:
pivot_table() - обязательно посмотреть !!!!!!!!!!!!!!!